<a href="https://colab.research.google.com/github/Matinnorouzi2023/Machin-learning/blob/main/Regression_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
x = np.array([1,2,3])   #  y = 2x+1
y = np.array([3,5,8])
plt.plot(x, y, "b.");

In [ ]:
X = np.c_[np.ones((3, 1)), x]          # add x0 = 1 to each instance
X

In [ ]:
theta = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
theta

In [ ]:
xtest  = np.array([[0], [2],[4]])
xtest

In [ ]:
xtestb = np.c_[np.ones((3, 1)), xtest]  # add x0 = 1 to each instance
xtestb

In [ ]:
ypred = xtestb.dot(theta)
ypred

In [ ]:
plt.plot(xtest, ypred, "r-")
plt.plot(x, y, "b.");

In [ ]:
# sklearn

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
x = np.array([1,2,3]).reshape(-1,1)
x

array([[1],
       [2],
       [3]])

In [ ]:
y = np.array([3,5,7]).reshape(-1,1)
y

array([[3],
       [5],
       [7]])

In [ ]:
model = LinearRegression()

In [ ]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [ ]:
model.intercept_    #y=ax+b

array([1.])

In [ ]:
model.coef_

array([[2.]])

In [ ]:
xtest  = np.array([[0], [2],[4]]).reshape(-1,1)
xtest

array([[0],
       [2],
       [4]])

In [ ]:
ypred = model.predict(xtest)
ypred

array([[1.],
       [5.],
       [9.]])